### ISSUE TITLE
Support ES256 

### ISSUE THREAD

**Issue by gembin** [slowli/jwt-compact#105]
Any plan to support `ES256:  ECDSA over P256 / SHA-256` ?

**Comment by slowli** [comment]
Hi! Terribly sorry for such a late response; for some reason, I didn't get a GitHub notification as usual. In general, I hesitate to add new supported algs to the crate; at its inception, the primary motivation was to implement "reasonable" non-standard (at the time) algs, such as `EdDSA` (over Curve25519) and `ES256K`. However, RSA algs were added since... If `ES256` is added, would it matter to you which crypto backend it would use (e.g., [`p256`](https://crates.io/crates/p256))? One thing that I certainly don't want to do is depending on OpenSSL 🙃

**Comment by gembin** [comment]
Thanks for your reply. Yes, [p256](https://crates.io/crates/p256) should be good, I also don't want OpenSSL.
