### ISSUE TITLE
x5t fails to parse depending on semantics used to generate it

### ISSUE THREAD

**Issue by balbifm** [slowli/jwt-compact#141]
Hi, we are getting an error when parsing a JWT, which looks like:

`Malformed token header: invalid length 40, expected base64url-encoded digest at line 1 column 147`

The library is expecting a 20 byte value as a result of base64, url-encoding the SHA-1 binary certificate's fingerprint.

But, the problem seems to be that there are providers that are using the hexa fingerprint (D2:7A:E1:4B:A2:40:BA:67:34:38:64:78:84:0A:52:7D:61:0E:70:F9) instead of the binary, which results in longer values. As an example, Auth0 seems to be doing [this](https://github.com/auth0/docs/blob/755b1ff7882b018dbab36b272d7b8baa5df1a605/articles/tokens/references/jwks-properties.md?plain=1#L31)

Other JWT libraries are not facing this issue, since they are using a String to hold that value, for example [jsonwebtoken](https://github.com/Keats/jsonwebtoken/blob/master/src/header.rs#L58)

Would it be possible to remove the array capacity from the x5t and x5t#S256 fields, so they are more flexible?

We can contribute the changes if needed.

**Comment by slowli** [comment]
Hi! A couple of questions to fully understand the issue:

- Does the `x5t` field still conform to the [RFC 7515 spec](https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.7) *in spirit* after the proposed changes are made? That is, is it true that `x5t` is still the SHA-1 thumbprint of the DER-encoded X.509 certificate of the signing key, but it may have a different encoding from the canonical base64-url? (E.g., `base64url(hex(sha1(certificate)))` like in the case of the Auth0 example you've provided.) If so, the problem is not with the `Header` field type, but rather with the decoding logic.
- In the case of Auth0, that's a bug on Auth0 side, which has been fixed, at least judging by [this forum post](https://community.auth0.com/t/jwk-certificate-thumbprint-is-invalid/16070/21); not sure why the docs aren't updated. Are there other providers that have the same or similar bug? In general, I'd like not to make the library worse than it can be because of bugs in other libraries, but this might be reconsidered if the bug is widespread enough.

**Comment by balbifm** [comment]
Hi, another example of a provider generated token not working with the library: https://docs.wso2.com/display/IS520/JWT+Token+Generation. In that documentation they are using 
`eyJhbGciOiJSUzI1NiIsIng1dCI6Ik5tSm1PR1V4TXpabFlqTTJaRFJoTlRabFlUQTFZemRoWlRSaU9XRTBOV0kyTTJKbU9UYzFaQSJ9.eyJodHRwOlwvXC93c28yLm9yZ1wvZ2F0ZXdheVwvYXBwbGljYXRpb25uYW1lIjoiT2F1dGg3IiwiZXhwIjoxNDUyNTk0ODkyLCJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJodHRwOlwvXC93c28yLm9yZ1wvZ2F0ZXdheVwvc3Vic2NyaWJlciI6ImFkbWluQGNhcmJvbi5zdXBlciIsImlzcyI6Imh0dHA6XC9cL3dzbzIub3JnXC9nYXRld2F5IiwiaHR0cDpcL1wvd3NvMi5vcmdcL2dhdGV3YXlcL2VuZHVzZXIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9yb2xlIjoiYWRtaW4sQXBwbGljYXRpb25cL2Rld3ZkZXcsQXBwbGljYXRpb25cL09hdXRoNyxJbnRlcm5hbFwvZXZlcnlvbmUiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9lbWFpbGFkZHJlc3MiOiJhZG1pbkB3c28yLmNvbSIsImlhdCI6MTQ1MjU5MzI1NCwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvb3JnYW5pemF0aW9uIjoiV1NPMiJ9.WRo2p92f-pt1vH9xfLgmrPWNKJfmST2QSPYcth7gXKz64LdP9zAMUtfAk9DVRdHTIQR3gX0jF4Ohb4UbNN4Oo97a35oTL1iRxIRTKUkh8L1dpt3H03Z0Ze7Q2giHGZikMIQv3gavHRYKjNMoU_1MuB90jiK7`
which fails to parse

**Comment by slowli** [comment]
@balbifm Would you mind taking a look at #142? I didn't convert thumbprints to plain `String`s, but rather to an enum that supports either a string or the previously used array representation.
